### ISSUE TITLE
gulp error

### ISSUE THREAD

**Issue by brecky** [spatie-custom/blender#247]
C:\xampp\htdocs\blender>gulp help
[16:51:28] Working directory changed to C:\xampp\htdocs
module.js:472
    throw err;
    ^

Error: Cannot find module 'laravel-elixir-vue-2'
    at Function.Module._resolveFilename (module.js:470:15)

C:\xampp\htdocs\blender>npm install laravel-elixir-vue-2
Blender@ C:\xampp\htdocs\blender
`-- laravel-elixir-vue-2@0.3.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
C:\xampp\htdocs\blender>gulp help
[16:55:22] Working directory changed to C:\xampp\htdocs
module.js:472
    throw err;
    ^

Error: Cannot find module 'laravel-elixir-vue-2'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\xampp\htdocs\gulpfile.js:3:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by sebastiandedeyne** [comment]
Most likely related to #246

**Comment by sebastiandedeyne** [comment]
Closing this for now. Feel free to reopen if you're still having issues.
