### ISSUE TITLE
gulp error - first install

### ISSUE THREAD

**Issue by evertramos** [spatie-custom/blender#38]
Hi there!

I got an error after following the installation process on gulp...

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:146:18)
    at node.js:404:3
```

What am I missing here?

Thanks!

**Comment by sebastiandedeyne** [comment]
You need to have webpack v1.x globally installed for the gulp setup.

**Comment by evertramos** [comment]
tks!
