### ISSUE TITLE
Gulp fails

### ISSUE THREAD

**Issue by mauritzbotha** [spatie-custom/blender#49]
I installed Blender according to the instructions, ran composer and NPM and then invoked gulp, but then I get the following:

gulp

/var/www/html/node_modules/blender-gulp/gulpfile.js:16
gulp.task('default', callback => {
                               ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/html/gulpfile.js:1:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by willemvb** [comment]
Have you checked `npm -v`? It should be greater than v.3. 
Also `webpack` should be installed globally (currently on version 1.13.1).

Does `gulp help` work? You can check version numbers there as well in the output.

**Comment by mauritzbotha** [comment]
Thanks Willem.
I did not use Homestead, just installed the system on a Amazon EC-2 instance.

npm -v
3.10.3
I installed webpack, then tried gulp help:

[ html]$ gulp help

/var/www/html/node_modules/blender-gulp/gulpfile.js:16
gulp.task('default', callback => {
                               ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/html/gulpfile.js:1:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by mauritzbotha** [comment]
Trying to invoke webpack:

[html]$ webpack

/var/www/html/node_modules/blender-gulp/config/webpack.js:8
const context = (context) => process.env.WEBPACK_CONTEXT === context;
                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/html/webpack.config.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by willemvb** [comment]
Can you check your node version as well with  `node -v`?
It should be 4.4 or higher  (I will add this requirement to the readme).
