### ISSUE TITLE
Error: spawn webpack ENOENT

### ISSUE THREAD

**Issue by yesayasoftware** [spatie-custom/blender#57]
Hello, I am using windows 10 and WAMP, I followed the instructions very well, but I got the above error "Error: spawn webpack ENOENT".

Here is the output from CMD.

[01:25:47] Using gulpfile C:\wamp64\www\blender\gulpfile.js
[01:25:47] Starting 'default'...
[01:25:47] Starting 'webpack'...
[01:25:47] Starting 'svg'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn webpack ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

Also, during npm install -g webpack, I received the warning below.

npm WARN optional Skipping failed optional dependency /webpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

Looking forward for your help.

Thanks

**Comment by willemvb** [comment]
We are not using this on Windows ourselves, so I cannot test this for now.
Some checks you can run:
- Can you run `webpack`in the project?
- What's the output of `gulp help`?
- Have you checked `npm -v`? It should be v.3 or higher. 
- Have you checked `node -v`? It should be v4.4 or higher.

**Comment by yesayasoftware** [comment]
Thanks for reply, I will try to install Homestead and let you know.

**Comment by yesayasoftware** [comment]
I have managed to install Homestead, and being able to run the application. Thanks.
